#ifndef BLOCK_ENUM_HPP
#define BLOCK_ENUM_HPP

enum BlockType
{
    LEFT_EXIT = 1,
    TOP_EXIT = 2,
    RIGHT_EXIT = 4,
    BOTTOM_EXIT = 8,

    LEFT_TOP_EXIT = LEFT_EXIT | TOP_EXIT,
    LEFT_RIGHT_EXIT = LEFT_EXIT | RIGHT_EXIT,
    LEFT_BOTTOM_EXIT = LEFT_EXIT | BOTTOM_EXIT,
    TOP_RIGHT_EXIT = TOP_EXIT | RIGHT_EXIT,
    TOP_BOTTOM_EXIT = TOP_EXIT | BOTTOM_EXIT,
    RIGHT_BOTTOM_EXIT = RIGHT_EXIT | BOTTOM_EXIT,

    LEFT_TOP_RIGHT_EXIT = LEFT_EXIT | TOP_EXIT | RIGHT_EXIT,
    LEFT_TOP_BOTTOM_EXIT = LEFT_EXIT | TOP_EXIT | BOTTOM_EXIT,
    LEFT_RIGHT_BOTTOM_EXIT = LEFT_EXIT | RIGHT_EXIT | BOTTOM_EXIT,
    TOP_RIGHT_BOTTOM_EXIT = TOP_EXIT | RIGHT_EXIT | BOTTOM_EXIT,

    LEFT_TOP_RIGHT_BOTTOM_EXIT = LEFT_EXIT | TOP_EXIT | RIGHT_EXIT | BOTTOM_EXIT,
};

#endif